service: lambda-s3-cleaner

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-south-1
  profile: serverless-admin
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::cert-s3-bucket"

functions:
  s3-cleaner:
    handler: handler.s3Cleaner
    events:
      - http:
          path: s3Cleaner
          method: get
          cors: true
      - schedule: rate(7 days)

plugins:
  - serverless-offline
